### ISSUE TITLE
porting to esp-01

### ISSUE THREAD

**Issue by alifilhan** [csnol/STM32-OTA#3]
@csnol 
I have a esp-01 module. I want to port the code to it so I an use it as a wireless programmer. Please tell me how to modify the code to use it on the esp-01

**Comment by csnol** [comment]
Hi, @alifilhan 
 You know,   We need 4 GPIOs  to OTA STM32
``` C++
* 2 output GPIOs for STM32's BOOT0 and RESET. 
* 2 GPIOs as a  EVEN Serial port to communicate with STM32.
```
You can use ESP-01's GPIO-0 and GPIO-2 (10K pullup both) to control BOOT0 and RESET
RX and TX to communicate with STM32.

Yes, That's all.

**Comment by alifilhan** [comment]
Thanks for replying. That means I just need to change the PIN 4 and PIN 5
to PIN 0 and PIN 2 only? Or I need to make more changes inside the code?

Thanks

**Comment by csnol** [comment]
@alifilhan 

Yes, no more code.
 helpful information. 
[https://www.instructables.com/id/How-to-use-the-ESP8266-01-pins/](url)

**Comment by alifilhan** [comment]
Thanks a lot. As I am done I am closing the issue
